language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - python3 setup.py build
  - python3 setup.py install
  - pip install pylint

script:
  - cd src && pylint main.py helpers.py -d global-statement,broad-except