language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
  - "pypy3.5"

before_install:
  - mv src/helpers.py tests/helpers.py

install:
  - pip install -r requirements.txt

script:
  - python tests/main.py