language: python
python:
  - "3.6"

before_install:
  - mv src/helpers.py tests/helpers.py

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - cd src && pylint main.py helpers.py