language: python
python:
  - "3.6"

before_install:
  - mv src/helpers.py tests/helpers.py

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - pylint src/main.py src/helpers.py src/test.py